wire [31:0] inst_IF;
wire [31:0] link_alu_out_IF;
wire [31:0] plus4_alu_out_IF;
wire [2:0] alu_op_IF;
wire wr_enable_IF;
wire itype_IF;
wire except_IF;
wire control_type_IF;
wire lui_IF;
wire slt_IF;
wire byte_load_IF;
wire word_we_IF;
wire byte_we_IF;
wire mem_read_IF;
wire shift_v_IF;
wire [1:0] shift_op_IF;
wire shift_IF;
wire load_ra_IF;
wire link_IF;
wire alu_b_zero_IF;
wire [2:0] branch_control_IF;
wire jr_IF;
wire [31:0] inst_ID;
wire [31:0] link_alu_out_ID;
wire [31:0] plus4_alu_out_ID;
wire [2:0] alu_op_ID;
wire wr_enable_ID;
wire itype_ID;
wire except_ID;
wire control_type_ID;
wire lui_ID;
wire slt_ID;
wire byte_load_ID;
wire word_we_ID;
wire byte_we_ID;
wire mem_read_ID;
wire shift_v_ID;
wire [1:0] shift_op_ID;
wire shift_ID;
wire load_ra_ID;
wire link_ID;
wire alu_b_zero_ID;
wire [2:0] branch_control_ID;
wire jr_ID;
wire [31:0] rs_data_ID;
wire [31:0] rt_data_ID;
wire [4:0] rs_num_ID;
wire [4:0] rt_num_ID;
wire [31:0] inst_EX;
wire [31:0] rs_data_EX;
wire [31:0] rt_data_EX;
wire [31:0] link_alu_out_EX;
wire [4:0] rs_num_EX;
wire [4:0] rt_num_EX;
wire [31:0] plus4_alu_out_EX;
wire [2:0] alu_op_EX;
wire wr_enable_EX;
wire itype_EX;
wire except_EX;
wire control_type_EX;
wire lui_EX;
wire slt_EX;
wire byte_load_EX;
wire word_we_EX;
wire byte_we_EX;
wire mem_read_EX;
wire shift_v_EX;
wire [1:0] shift_op_EX;
wire shift_EX;
wire load_ra_EX;
wire link_EX;
wire alu_b_zero_EX;
wire [2:0] branch_control_EX;
wire jr_EX;
wire [31:0] alu_out_EX;
wire [4:0] rd_num_EX;
wire [31:0] link_out_EX;
wire [31:0] alu_out_MEM;
wire [31:0] rt_data_MEM;
wire [4:0] rd_num_MEM;
wire [31:0] link_out_MEM;
wire [4:0] rs_num_MEM;
wire [4:0] rt_num_MEM;
wire [2:0] alu_op_MEM;
wire wr_enable_MEM;
wire itype_MEM;
wire except_MEM;
wire control_type_MEM;
wire lui_MEM;
wire slt_MEM;
wire byte_load_MEM;
wire word_we_MEM;
wire byte_we_MEM;
wire mem_read_MEM;
wire shift_v_MEM;
wire [1:0] shift_op_MEM;
wire shift_MEM;
wire load_ra_MEM;
wire link_MEM;
wire alu_b_zero_MEM;
wire [2:0] branch_control_MEM;
wire jr_MEM;
wire [31:0] data_out_MEM;
wire [31:0] alu_out_WB;
wire [31:0] data_out_WB;
wire [4:0] rd_num_WB;
wire [31:0] link_out_WB;
wire [2:0] alu_op_WB;
wire wr_enable_WB;
wire itype_WB;
wire except_WB;
wire control_type_WB;
wire lui_WB;
wire slt_WB;
wire byte_load_WB;
wire word_we_WB;
wire byte_we_WB;
wire mem_read_WB;
wire shift_v_WB;
wire [1:0] shift_op_WB;
wire shift_WB;
wire load_ra_WB;
wire link_WB;
wire alu_b_zero_WB;
wire [2:0] branch_control_WB;
wire jr_WB;
